# Generated by Django 6.0.7 on 2026-07-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_post_remove_entryimage_entry_postimage_delete_entry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.RemoveConstraint(
            model_name='postimage',
            name='unique_post_image_position',
        ),
        migrations.AddField(
            model_name='postimage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='guestbook/thumbnails/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='guestbook/originals/%Y/%m/%d/'),
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='position',
        ),
    ]
