# Generated by Django 6.0.7 on 2026-08-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_alter_post_options_alter_postimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='guestbook/originals/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, upload_to='guestbook/thumbnails/%Y/%m/%d/'),
        ),
    ]
